services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1 

  listener-service:
    build:
      context: ./../listener-service
      # 使用指定的 Dockerfile
      dockerfile: listener-service.dockerfile
    deploy:
      mode: replicated # 副本模式
      replicas: 1 # 启动一个副本

  mailer-service:
    build:
      context: ./../mail-service
      dockerfile: mail-service.dockerfile
    restart: always # 容器异常退出或 Docker 重启时自动拉起
    deploy:
      mode: replicated # 副本模式
      replicas: 1 # 启动一个副本
    environment:
      MAIL_DOMAIN: ${MAIL_DOMAIN}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FROM_NAME: ${FROM_NAME}
      FROM_ADDRESS: ${FROM_ADDRESS}

  logger-service:
    build:
      context: ./../logger-service
      dockerfile: logger-service.dockerfile
    restart: always 
    deploy:
      mode: replicated
      replicas: 1
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      ACCESS_SECRET: ${ACCESS_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      REDIRECT_URL: ${REDIRECT_URL}

  post-service:
    build:
      context: ./../post-service
      dockerfile: post-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5633:5432" 
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    ports:
      - '5672:5672'
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/

  redis:
    image: 'redis:8.4-alpine'
    ports:
      - '6379:6379'
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/redis/:/data
